apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: version-product
  labels:
    app: version-app
    l2: label
    l3: label3
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/andrii-codefresh/argocd-example-apps1.git
    targetRevision: HEAD
  destination:
    server: https://localhost:64182
    namespace: gr
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
